name: 'Nullify DAST Action'
description: 'Test your API endpoints with Nullify DAST'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  app-name:
    description: Name of the application to be tested
    required: true
  spec-path:
    description: Absolute directory of the API specification to be tested
    required: true
  target-host:
    description: Target host endpoint of the application to be tested
    required: true
  base-args:
    description: Space-separated arguments to include (e.g. -d, -v for debug and verbose modes)
    required: false
    default: "-v"
  github-repository:
    description: Name of the GitHub repository
    required: false
    default: ${{ github.repository }}
  github-token:
    description: GitHub API token which will be exchanged for a Nullify token
    required: false
    default: ${{ github.token }}
  header:
    description: Header to include in authorization request
    required: false
  nullify-host:
    description: Nullify API host e.g. api.nullify.ai
    required: false
    default: "api.nullify.ai"
  nullify-version:
    description: Nullify CLI version to be used
    required: false
    default: "0.10.12"
  os-arch:
    description: Nullify CLI 'OS Arch' to be used with default `linux_amd64`
    required: false
    default: "linux_amd64"
  local:
    description: Nullify dynamic analysis scan run locally
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install Nullify CLI
      shell: sh
      run: |
        download_url="https://github.com/Nullify-Platform/cli/releases/download/v${{ inputs.nullify-version }}/nullify_${{ inputs.os-arch }}_${{ inputs.nullify-version }}"
        wget -q $download_url -O ./nullify
        sudo chmod +x ./nullify
    - name: Execute Nullify DAST
      if: ${{ inputs.local == 'true' }}
      shell: sh
      run: |
        repo_fullname=${{ inputs.github-repository }}
        repo_owner=${repo_fullname%%/*}
        repo_name=${repo_fullname#*/}
        export GITHUB_ACTIONS=true
        export GITHUB_ACTION_REPOSITORY=${{ github.repository }}
        ./nullify ${{ inputs.base-args }} \
          --host "${{ inputs.nullify-host }}" \
          --github-token "${{ inputs.github-token }}" \
          dast \
            --local \
            --app-name "${{ inputs.app-name }}" \
            --spec-path "${{ inputs.spec-path }}" \
            --target-host "${{ inputs.target-host }}" \
            --github-owner "$repo_owner" \
            --github-repo "$repo_name" \
            --header "${{ inputs.header }}"
    - name: Execute Nullify DAST
      if: ${{ inputs.local != 'true' }}
      shell: sh
      run: |
        repo_fullname=${{ inputs.github-repository }}
        repo_owner=${repo_fullname%%/*}
        repo_name=${repo_fullname#*/}
        export GITHUB_ACTIONS=true
        export GITHUB_ACTION_REPOSITORY=${{ github.repository }}
        ./nullify ${{ inputs.base-args }} \
          --host "${{ inputs.nullify-host }}" \
          --github-token "${{ inputs.github-token }}" \
          dast \
            --app-name "${{ inputs.app-name }}" \
            --spec-path "${{ inputs.spec-path }}" \
            --target-host "${{ inputs.target-host }}" \
            --github-owner "$repo_owner" \
            --github-repo "$repo_name" \
            --header "${{ inputs.header }}"
