name: 'Nullify DAST Action'
description: 'Test your API endpoints with Nullify DAST'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  app-name:
    description: Name of the application to be tested
    required: true
  spec-path:
    description: Absolute directory of the API specification to be tested
    required: true
  target-host:
    description: Target host endpoint of the application to be tested
    required: true
  base-args:
    description: Space-separated arguments to include (e.g. -d, -v for debug and verbose modes)
    required: false
    default: "-v"
  github-repository:
    description: Name of the GitHub repository
    required: false
    default: ${{ github.repository }}
  github-token:
    description: GitHub API token which will be exchanged for a Nullify token
    required: false
    default: ${{ github.token }}
  header:
    description: Header to include in authorization request
    required: false
  auth-method:
    description: Authentication method to use (basic, bearer, session, oauth2, jwt, custom)
    required: false
    default: "bearer"
  auth-username:
    description: Username for Basic Auth authentication
    required: false
  auth-user-description:
    description: Description for the user
    required: false
  auth-password:
    description: Password for Basic Auth authentication
    required: false
  auth-token:
    description: Token for Bearer Token, JWT, or OAuth2 authentication
    required: false
  auth-client-id:
    description: Client ID for OAuth2 authentication
    required: false
  auth-client-secret:
    description: Client Secret for OAuth2 authentication
    required: false
  auth-token-url:
    description: Token URL for OAuth2 authentication
    required: false
  auth-scope:
    description: Scope for OAuth2 authentication
    required: false
  auth-login-url:
    description: URL to perform login for session-based authentication
    required: false
  auth-login-body:
    description: JSON body to send for session-based authentication login
    required: false
  auth-login-selector:
    description: CSS selector to extract session token/cookie from login response
    required: false
  auth-custom-headers:
    description: JSON string of custom headers for authentication
    required: false
  auth-custom-params:
    description: JSON string of custom query parameters for authentication
    required: false
  user-1-role:
    description: Role for user 1
    required: false
  user-1-auth-method:
    description: Authentication method for user 1
    required: false
  user-1-username:
    descript ion: Username for user 1
    required: false
  user-1-password:
    description: Password for user 1
    required: false
  user-1-token:
    description: Token for user 1
    required: false
  user-1-client-id:
    description: Client ID for user 1
    required: false
  user-1-client-secret:
    description: Client Secret for user 1
    required: false
  user-1-token-url:
    description: Token URL for user 1
    required: false
  user-1-scope:
    description: Scope for user 1
    required: false
  user-1-login-url:
    description: Login URL for user 1
    required: false
  user-1-login-body:
    description: Login body for user 1
    required: false
  user-1-login-selector:
    description: Login selector for user 1
    required: false
  user-1-custom-headers:
    description: Custom headers for user 1
    required: false
  user-1-custom-params:
    description: Custom params for user 1
    required: false
  user-1-description:
    description: Description for user 1
    required: false
  user-2-role:
    description: Role for user 2
    required: false
  user-2-auth-method:
    description: Authentication method for user 2
    required: false
  user-2-username:
    description: Username for user 2
    required: false
  user-2-password:
    description: Password for user 2
    required: false
  user-2-token:
    description: Token for user 2
    required: false
  user-2-client-id:
    description: Client ID for user 2
    required: false   
  user-2-client-secret:
    description: Client Secret for user 2
    required: false
  user-2-token-url:
    description: Token URL for user 2
    required: false
  user-2-scope:
    description: Scope for user 2
    required: false
  user-2-login-url:
    description: Login URL for user 2
    required: false
  user-2-login-body:
    description: Login body for user 2  
    required: false
  user-2-login-selector:
    description: Login selector for user 2
    required: false
  user-2-custom-headers:
    description: Custom headers for user 2
    required: false
  user-2-custom-params:
    description: Custom params for user 2
    required: false
  user-2-description:
    description: Description for user 2
    required: false
  user-3-role:
    description: Role for user 3
    required: false
  user-3-auth-method:
    description: Authentication method for user 3
    required: false
  user-3-username:
    description: Username for user 3
    required: false
  user-3-password:
    description: Password for user 3
    required: false
  user-3-token:
    description: Token for user 3
    required: false
  user-3-client-id:
    description: Client ID for user 3
    required: false
  user-3-client-secret:
    description: Client Secret for user 3
    required: false
  user-3-token-url:
    description: Token URL for user 3
    required: false
  user-3-scope:
    description: Scope for user 3
    required: false
  user-3-login-url:
    description: Login URL for user 3
    required: false
  user-3-login-body:
    description: Login body for user 3
    required: false
  user-3-login-selector:
    description: Login selector for user 3
    required: false
  user-3-custom-headers:
    description: Custom headers for user 3
    required: false
  user-3-custom-params:
    description: Custom params for user 3
    required: false
  user-3-description:
    description: Description for user 3
    required: false
  user-4-role:
    description: Role for user 4
    required: false
  user-4-auth-method:
    description: Authentication method for user 4
    required: false
  user-4-username:
    description: Username for user 4
    required: false
  user-4-password:
    description: Password for user 4
    required: false
  user-4-token:
    description: Token for user 4
    required: false
  user-4-client-id:
    description: Client ID for user 4
    required: false
  user-4-client-secret:
    description: Client Secret for user 4
    required: false
  user-4-token-url:
    description: Token URL for user 4
    required: false
  user-4-scope:
    description: Scope for user 4
    required: false
  user-4-login-url:
    description: Login URL for user 4
    required: false
  user-4-login-body:
    description: Login body for user 4
    required: false
  user-4-login-selector:
    description: Login selector for user 4
    required: false
  user-4-custom-headers:
    description: Custom headers for user 4
    required: false
  user-4-custom-params:
    description: Custom params for user 4
    required: false
  user-4-description:
    description: Description for user 4
    required: false
  nullify-host:
    description: Nullify API host e.g. api.nullify.ai
    required: false
    default: "api.nullify.ai"
  nullify-version:
    description: Nullify CLI version to be used
    required: false
    default: "0.11.4"
  os-arch:
    description: Nullify CLI 'OS Arch' to be used with default `linux_amd64`
    required: false
    default: "linux_amd64"
  local:
    description: Nullify dynamic analysis scan run locally
    required: false
    default: 'false'
  image-label:
    description: Label to identify the Docker image to use for the scan
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Nullify CLI
      shell: sh
      run: |
        download_url="https://github.com/Nullify-Platform/cli/releases/download/v${{ inputs.nullify-version }}/nullify_${{ inputs.os-arch }}_${{ inputs.nullify-version }}"
        wget -q $download_url -O ./nullify
        sudo chmod +x ./nullify
    - name: Setup Authentication
      shell: bash
      run: |
        if [ -f "${GITHUB_WORKSPACE}/scripts/setup_auth.sh" ]; then
          bash "${GITHUB_WORKSPACE}/scripts/setup_auth.sh" ~/.nullify/auth_config.json
        else
          echo "Warning: setup_auth.sh script not found"
        fi
    - name: Execute Nullify DAST
      if: ${{ inputs.local == 'true' }}
      shell: sh
      run: |
        repo_fullname=${{ inputs.github-repository }}
        repo_owner=${repo_fullname%%/*}
        repo_name=${repo_fullname#*/}
        export GITHUB_ACTIONS=true
        export GITHUB_ACTION_REPOSITORY=${{ github.repository }}
        
        # Determine auth arguments
        AUTH_ARGS=""
        if [ ! -z "${{ inputs.header }}" ]; then
          AUTH_ARGS="--header \"${{ inputs.header }}\""
        elif [ -f ~/.nullify/auth_config.json ]; then
          AUTH_ARGS="--auth-config ~/.nullify/auth_config.json"
        fi
        
        ./nullify ${{ inputs.base-args }} \
          --host "${{ inputs.nullify-host }}" \
          --github-token "${{ inputs.github-token }}" \
          dast \
            --local \
            --app-name "${{ inputs.app-name }}" \
            --spec-path "${{ inputs.spec-path }}" \
            --target-host "${{ inputs.target-host }}" \
            --github-owner "$repo_owner" \
            --github-repo "$repo_name" \
            $AUTH_ARGS \
            ${{ inputs.image-label != '' && format('--image-label "{0}"', inputs.image-label) || '' }}
            
    - name: Execute Nullify DAST
      if: ${{ inputs.local != 'true' }}
      shell: sh
      run: |
        repo_fullname=${{ inputs.github-repository }}
        repo_owner=${repo_fullname%%/*}
        repo_name=${repo_fullname#*/}
        export GITHUB_ACTIONS=true
        export GITHUB_ACTION_REPOSITORY=${{ github.repository }}
        
        # Determine auth arguments
        AUTH_ARGS=""
        if [ ! -z "${{ inputs.header }}" ]; then
          AUTH_ARGS="--header \"${{ inputs.header }}\""
        elif [ -f ~/.nullify/auth_config.json ]; then
          AUTH_ARGS="--auth-config ~/.nullify/auth_config.json"
        fi
        
        ./nullify ${{ inputs.base-args }} \
          --host "${{ inputs.nullify-host }}" \
          --github-token "${{ inputs.github-token }}" \
          dast \
            --app-name "${{ inputs.app-name }}" \
            --spec-path "${{ inputs.spec-path }}" \
            --target-host "${{ inputs.target-host }}" \
            --github-owner "$repo_owner" \
            --github-repo "$repo_name" \
            $AUTH_ARGS \
            ${{ inputs.image-label != '' && format('--image-label "{0}"', inputs.image-label) || '' }}
