name: "build"
on:
  pull_request:
env:
  NULLIFY_VERSION: 0.0.0
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nullify
        run: |
          wget -q https://github.com/Nullify-Platform/cli/releases/download/v${{ env.NULLIFY_VERSION }}/nullify_linux_amd64_${{ env.NULLIFY_VERSION }} -O nullify
          chmod +x nullify
      - name: Test
        run: |
          ./nullify -d
