name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: release
  cancel-in-progress: true
run-name: Release by @${{ github.actor }} ${{ github.sha }}
permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: read
jobs:
  get-version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Release Version
        id: get-version
        uses: nullify-platform/github-actions/actions/release-version@main
  release:
    if: ${{ needs.get-version.outputs.version != 'undefined' }}
    name: Release
    runs-on: ubuntu-latest
    needs: [ get-version]
    steps:
      - name: Generate Release
        uses: softprops/action-gh-release@v2
        env:
          VERSION: ${{ needs.get-version.outputs.version }}
        with:
          draft: false
          generate_release_notes: true
          append_body: true
          tag_name: v${{ env.VERSION }}
          token: ${{ github.token }}
